
  // This file is auto-generated. Do not edit manually.
  export const environment = {
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "APPDATA": "C:\\Users\\Robert\\AppData\\Roaming",
    "asl.log": "Destination=file",
    "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
    "ChocolateyLastPathUpdate": "133518254516764655",
    "CLIENT_PORT": "8082",
    "COLOR": "1",
    "CommonProgramFiles": "C:\\Program Files\\Common Files",
    "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
    "CommonProgramW6432": "C:\\Program Files\\Common Files",
    "COMPUTERNAME": "DESKTOP-UI9FSP8",
    "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
    "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
    "EDITOR": "C:\\WINDOWS\\notepad.exe",
    "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
    "FPS_BROWSER_USER_PROFILE_STRING": "Default",
    "GNUPLOT_LIB": "C:\\Program Files\\gnuplot\\demo;C:\\Program Files\\gnuplot\\demo\\games;C:\\Program Files\\gnuplot\\share",
    "GNUTERM": "windows",
    "GRADLE_HOME": "E:\\gradle",
    "HOME": "C:\\Users\\Robert",
    "HOMEDRIVE": "C:",
    "HOMEPATH": "\\Users\\Robert",
    "INIT_CWD": "H:\\projects\\Javascript\\game-frame\\packages\\mobile-client",
    "JAVA_HOME": "C:\\Program Files\\Java\\jdk-21",
    "JetBrains Rider": "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.2.3\\bin;",
    "LOCALAPPDATA": "C:\\Users\\Robert\\AppData\\Local",
    "LOGONSERVER": "\\\\DESKTOP-UI9FSP8",
    "NODE": "C:\\Program Files (x86)\\nodejs\\node.exe",
    "NODE_EXE": "C:\\Program Files (x86)\\nodejs\\\\node.exe",
    "NPM_CLI_JS": "C:\\Users\\Robert\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
    "npm_command": "run-script",
    "npm_config_cache": "C:\\Users\\Robert\\AppData\\Local\\npm-cache",
    "npm_config_globalconfig": "C:\\Users\\Robert\\AppData\\Roaming\\npm\\etc\\npmrc",
    "npm_config_global_prefix": "C:\\Users\\Robert\\AppData\\Roaming\\npm",
    "npm_config_init_module": "C:\\Users\\Robert\\.npm-init.js",
    "npm_config_local_prefix": "H:\\projects\\Javascript\\game-frame\\packages\\mobile-client",
    "npm_config_node_gyp": "C:\\Users\\Robert\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
    "npm_config_noproxy": "",
    "npm_config_npm_version": "10.5.0",
    "npm_config_prefix": "C:\\Users\\Robert\\AppData\\Roaming\\npm",
    "npm_config_userconfig": "C:\\Users\\Robert\\.npmrc",
    "npm_config_user_agent": "npm/10.5.0 node/v20.11.0 win32 x64 workspaces/false",
    "npm_execpath": "C:\\Users\\Robert\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
    "npm_lifecycle_event": "generate-env",
    "npm_lifecycle_script": "tsc  generate-env.ts && node generate-env.js",
    "npm_node_execpath": "C:\\Program Files (x86)\\nodejs\\node.exe",
    "npm_package_json": "H:\\projects\\Javascript\\game-frame\\packages\\mobile-client\\package.json",
    "npm_package_name": "mobileclient",
    "npm_package_version": "1.0.0",
    "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\Robert\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
    "NUMBER_OF_PROCESSORS": "12",
    "NVM_HOME": "C:\\Users\\Robert\\AppData\\Roaming\\nvm",
    "NVM_SYMLINK": "C:\\Program Files\\nodejs",
    "OculusBase": "C:\\Program Files\\Oculus\\",
    "OneDrive": "C:\\Users\\Robert\\OneDrive",
    "OneDriveConsumer": "C:\\Users\\Robert\\OneDrive",
    "OnlineServices": "Online Services",
    "OS": "Windows_NT",
    "Path": "H:\\projects\\Javascript\\game-frame\\packages\\mobile-client\\node_modules\\.bin;H:\\projects\\Javascript\\game-frame\\packages\\node_modules\\.bin;H:\\projects\\Javascript\\game-frame\\node_modules\\.bin;H:\\projects\\Javascript\\node_modules\\.bin;H:\\projects\\node_modules\\.bin;H:\\node_modules\\.bin;C:\\Users\\Robert\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\java8path;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Python312\\Scripts\\;C:\\Python312\\;C:\\Program Files\\Oculus\\Support\\oculus-runtime;C:\\Program Files (x86)\\Razer Chroma SDK\\bin;C:\\Program Files\\Razer Chroma SDK\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Users\\Robert\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Calibre2\\;C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps;C:\\WINDOWS\\system32\\config\\systemprofile\\.dnx\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\dotnet\\;C:\\Users\\Robert\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\nodejs\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\GitHub CLI\\;C:\\Program Files\\CMake\\bin;C:\\Program Files\\gnuplot\\bin;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Program Files\\gnuplot\\bin\\;C:\\Ruby24-x64\\bin;C:\\Users\\Robert\\AppData\\Local\\Microsoft\\WindowsApps;E:\\maven\\bin;E:\\gradle\\bin;C:\\Users\\Robert\\.dotnet\\tools;C:\\Users\\Robert\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Users\\Robert\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\JetBrains\\JetBrains Rider 2023.2.3\\bin;C:\\Program Files\\Notepad++\\;C:\\Users\\Robert\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Robert\\AppData\\Local\\gitkraken\\bin;C:\\Program Files (x86)\\NUnit.org\\nunit-console;C:\\Users\\Robert\\AppData\\Local\\JetBrains\\Toolbox\\scripts;C:\\Users\\Robert\\.dotnet\\tools;C:\\Users\\Robert\\AppData\\Roaming\\npm;C:\\Users\\Robert\\AppData\\Local\\Programs\\Swift\\Runtimes\\5.10.1\\usr\\bin\\;C:\\Users\\Robert\\AppData\\Local\\Programs\\Swift\\Toolchains\\5.10.1+Asserts\\usr\\bin\\;C:\\Users\\Robert\\AppData\\Local\\Programs\\Swift\\Tools\\5.10.1\\;e:\\Cygwin64\\bin;C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin;",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.RB;.RBW",
    "Platform": "HPD",
    "platformcode": "6J",
    "PROCESSOR_ARCHITECTURE": "AMD64",
    "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 63 Stepping 2, GenuineIntel",
    "PROCESSOR_LEVEL": "6",
    "PROCESSOR_REVISION": "3f02",
    "ProgramData": "C:\\ProgramData",
    "ProgramFiles": "C:\\Program Files",
    "ProgramFiles(x86)": "C:\\Program Files (x86)",
    "ProgramW6432": "C:\\Program Files",
    "PROMPT": "$P$G",
    "PSModulePath": "C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\",
    "PUBLIC": "C:\\Users\\Public",
    "RegionCode": "NA",
    "SDKROOT": "C:\\Users\\Robert\\AppData\\Local\\Programs\\Swift\\Platforms\\5.10.1\\Windows.platform\\Developer\\SDKs\\Windows.sdk\\",
    "SERVER_PORT": "3035",
    "SESSIONNAME": "Console",
    "SystemDrive": "C:",
    "SystemRoot": "C:\\WINDOWS",
    "TEMP": "C:\\Users\\Robert\\AppData\\Local\\Temp",
    "TMP": "C:\\Users\\Robert\\AppData\\Local\\Temp",
    "USERDOMAIN": "DESKTOP-UI9FSP8",
    "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-UI9FSP8",
    "USERNAME": "Robert",
    "USERPROFILE": "C:\\Users\\Robert",
    "VS110COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\",
    "VS120COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\",
    "VS140COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
    "VSSDK140Install": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
    "windir": "C:\\WINDOWS",
    "__PSLockDownPolicy": "0",
  } as const;
